import time

# ==========================================
# 1. foundation api
# only print for now. TODO: replace with real APIs
# ==========================================

def api_set_torso_pitch(angle: float, speed: float):
    print(f"[Hardware] Torso turn angle to: {angle}, speed: {speed}")

def api_blend_arm_pose(target_pose: str, duration: float):
    print(f"[Hardware] arms shift to pose: '{target_pose}', spend time: {duration}s")

def api_play_idle_animation():
    print(f"[Hardware] idling...")

# ==========================================
# 2. sandbox to execute code generated by VLM
# ==========================================

def execute_vlm_code_in_sandbox(python_code_str: str):
    '''
    execute VLM python code in sandbox
    '''
    print("\n>>> Start executing VLM code >>>")
    
    # build sandbox
    # only allow limited functions and modules (such as time)
    safe_globals = {
        "__builtins__": {},  # ban default functions (such as open, eval, import, etc.)
        "set_torso_pitch": api_set_torso_pitch,
        "blend_arm_pose": api_blend_arm_pose,
        "play_idle_animation": api_play_idle_animation,
        "time": time         # using time.sleep() to control the sequence
    }
    
    # capture local var during execution
    safe_locals = {}

    try:
        exec(python_code_str, safe_globals, safe_locals)
        print("<<< VLM code execution complete <<<")
        
    except Exception as e:
        # capture exceptions
        print(f"\n[sandbox blocking] exceptions: {e}")
        print("trigger Fallback Policy...")

# ==========================================
# 3. test
# ==========================================

if __name__ == "__main__":
    # temp simulation of VLM code
    valid_vlm_code = '''
set_torso_pitch(-0.2, 0.5)
time.sleep(1.0)
blend_arm_pose('wave', 2.0)
'''
    execute_vlm_code_in_sandbox(valid_vlm_code)

    # simulate VLM hallucination
    hallucination_code = '''
import os
os.system("echo 'rm'")
undefined_function()
'''
    execute_vlm_code_in_sandbox(hallucination_code)